apiVersion: v1
kind: Namespace
metadata:
  name: dbaas-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbaas-controller
  namespace: dbaas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaas-controller
rules:
- apiGroups: ["dbaas.wso2.com"]
  resources: ["dbinstances", "dbsnapshots", "dbparametergroups"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["dbaas.wso2.com"]
  resources: ["dbinstances/status", "dbsnapshots/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["dbaas.wso2.com"]
  resources: ["dbinstances/finalizers", "dbsnapshots/finalizers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["kubeovn.io"]
  resources: ["vpcs"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["kubeovn.io"]
  resources: ["subnets"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["kubeovn.io"]
  resources: ["vpc-peerings"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["harvesterhci.io"]
  resources: ["virtualmachineimages"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dbaas-controller
subjects:
- kind: ServiceAccount
  name: dbaas-controller
  namespace: dbaas-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbaas-controller
